spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  kafka:
    consumer:
      group-id: shop.1
  application:
    name: shopbook
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8082